### PR TITLE
Enable Nitpicky mode

### PR DESCRIPTION
**Pull request by jeffreypaul15**
Nitpicky stuff from #6 
Does this need a changelog?

### CODE REVIEW

**Comment by nabobalis** [comment]
No its ok.

**Comment by nabobalis** [comment]
```
/home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/sunkit_pyvista/plotter.py:docstring of sunkit_pyvista.plotter.SunpyPlotter:: WARNING: py:class reference target not found: astropy.coordinates.BaseFrame
/home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/pyvista/plotting/plotting.py:docstring of pyvista.plotting.plotting.Plotter.show:: WARNING: py:class reference target not found: string
/home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/pyvista/plotting/plotting.py:docstring of pyvista.plotting.plotting.Plotter.show:: WARNING: py:class reference target not found: floats
```
Looks like three left.

**Comment by jeffreypaul15** [comment]
> ```
> /home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/sunkit_pyvista/plotter.py:docstring of sunkit_pyvista.plotter.SunpyPlotter:: WARNING: py:class reference target not found: astropy.coordinates.BaseFrame
> /home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/pyvista/plotting/plotting.py:docstring of pyvista.plotting.plotting.Plotter.show:: WARNING: py:class reference target not found: string
> /home/vsts/work/1/s/.tox/build_docs/lib/python3.8/site-packages/pyvista/plotting/plotting.py:docstring of pyvista.plotting.plotting.Plotter.show:: WARNING: py:class reference target not found: floats
> ```
> 
> Looks like three left.

One for us though, the other 2 are Pyvista's docstrings right?

**Comment by nabobalis** [comment]
True but I assume this comes from the show in our code as it wraps the pyvista one.

**Comment by jeffreypaul15** [comment]
> True but I assume this comes from the show in our code as it wraps the pyvista one.

How do we fix this then?

**Comment by nabobalis** [comment]
Not sure.

**Comment by dstansby** [comment]
I would
- Add them to nitpick ignore
- Raise an upstream issue with `pyvista` to fix them

**Comment by jeffreypaul15** [comment]
>     * Raise an upstream issue with `pyvista` to fix them

Pyvista's codebase is filled with these dcstring issues though

**Comment by dstansby** [comment]
Okay, lets leave this as is then, and we can re-asses if we come upon more pyvista issues in the future.

**Pull request merged**
